AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lamdbda RDS mysql

Resources:
  SimpleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Runtime: nodejs14.x
      Handler: index.lambdaHandler
      Environment:
        Variables:
          NODE_ENV : development
          DB_DATABASE : vins_test1
          DB_HOST : test-db.cgnygp2k8wdr.eu-west-1.rds.amazonaws.com
          DB_USER : vincenzo.francavilla
          DB_PASSWD : bAD3#r0s1ech0SPiRE9l
          REGION: eu-west-1
      VpcConfig:
          SecurityGroupIds:
            - sg-9fa84eef
          SubnetIds:
            - subnet-bb83f5f3
      Layers:
        - arn:aws:lambda:eu-west-1:275552291381:layer:mysql2:1

